services:
  mysql:
    image: mysql:8.0
    container_name: thermostat-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Kassan1!
      MYSQL_DATABASE: thermostat
      MYSQL_USER: thermostat
      MYSQL_PASSWORD: Thermostat1!
      TZ: Europe/Stockholm
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost  -u $$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 1s
      timeout: 20s
      retries: 30

  rabbitmq:
    image: docker.io/library/rabbitmq:4.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 30s
      retries: 30

  thermostat:
    container_name: thermostat
    build:
      context: ./thermostat-service/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      MYSQL_URI: thermostat-mysql:3306
      MYSQL_DATABASE: thermostat
      MYSQL_USER: thermostat
      MYSQL_PASSWORD: Thermostat1!
      TEMPERATURE_SENSORS: "temperature-sensor-spring-1,temperature-sensor-spring-2,temperature-sensor-1"
      DEFAULT_TEMPERATURE_SENSOR: temperature-sensor-spring-1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health" ]
      interval: 1s
      timeout: 10s
      retries: 60
    depends_on:
      mysql:
        condition: service_healthy

  temperature-sensor-spring-1:
    container_name: temperature-sensor-spring-1
    build:
      context: ./tempsensor-service-spring/
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  temperature-sensor-spring-2:
    container_name: temperature-sensor-spring-2
    build:
      context: ./tempsensor-service-spring/
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  temperature-sensor-1:
    container_name: temperature-sensor-1
    build:
      context: ./tempsensor-service/
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      TEMPERATURE_INCREMENT: 0.4
      TEMPERATURE_DECREMENT: 0.2
      MIN_TEMPERATURE: -42
      MAX_TEMPERATURE: 42
      INITIAL_TEMPERATURE: 21
      RANDOM_INITIAL_TEMPERATURE: true
      TEMPERATURE_UPDATE_INTERVAL: 2s
      TEMPERATURE_STREAM_INTERVAL: 1s
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health" ]
      interval: 1s
      timeout: 10s
      retries: 60
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  mysql_data:
