se.ductus.tempsensor.temperature.sensor-id=${TEMPERATURE_SENSOR_ID:}
se.ductus.tempsensor.temperature.increment=${TEMPERATURE_INCREMENT:0.8}
se.ductus.tempsensor.temperature.decrement=${TEMPERATURE_DECREMENT:0.4}
se.ductus.tempsensor.temperature.minimum=${MIN_TEMPERATURE:-40}
se.ductus.tempsensor.temperature.maximum=${MAX_TEMPERATURE:35}
se.ductus.tempsensor.temperature.initial=${INITIAL_TEMPERATURE:0}
se.ductus.tempsensor.temperature.random-initial-value=${RANDOM_INITIAL_TEMPERATURE:false}

se.ductus.tempsensor.temperature-update-interval=${TEMPERATURE_UPDATE_INTERVAL:1s}
se.ductus.tempsensor.temperature-stream-interval=${TEMPERATURE_STREAM_INTERVAL:off}

mp.messaging.outgoing.temperature-updates.connector=smallrye-rabbitmq
mp.messaging.outgoing.temperature-updates.exchange.name=temperature

quarkus.rabbitmq.devservices.image-name=docker.io/library/rabbitmq:4.2-management

quarkus.swagger-ui.always-include=true
