se.ductus.tempsensor.temperature.increment=${TEMPERATURE_INCREMENT:0.8}
se.ductus.tempsensor.temperature.decrement=${TEMPERATURE_DECREMENT:0.4}
se.ductus.tempsensor.temperature.minimum=${MIN_TEMPERATURE:-40}
se.ductus.tempsensor.temperature.maximum=${MAX_TEMPERATURE:35}
se.ductus.tempsensor.temperature.initial=${INITIAL_TEMPERATURE:0}
se.ductus.tempsensor.temperature.random-initial-value=${RANDOM_INITIAL_TEMPERATURE:false}

quarkus.swagger-ui.always-include=true
