se.ductus.temperature.streamer.temperature-stream-interval=${TEMPERATURE_STREAM_INTERVAL:off}

mp.messaging.outgoing.temperature-updates.connector=smallrye-rabbitmq
mp.messaging.outgoing.temperature-updates.exchange.name=temperature
mp.messaging.outgoing.temperature-updates.default-routing-key=temperature.sensor

quarkus.rabbitmq.devservices.image-name=docker.io/library/rabbitmq:4.2-management

se.ductus.temperature.streamer.temperature-sensors=${TEMPERATURE_SENSORS}
quarkus.rest-client.temperature-sensor.url=http://unknown:8080
