quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${MYSQL_USER}
quarkus.datasource.password=${MYSQL_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:mysql://${MYSQL_URI}/${MYSQL_DATABASE}
quarkus.flyway.migrate-at-start=true

quarkus.scheduler.enabled=true

quarkus.rest-client.temperature-sensor.url=http://${DEFAULT_TEMPERATURE_SENSOR}:8080

se.ductus.thermostat.temperature-sensors=${TEMPERATURE_SENSORS}

quarkus.swagger-ui.always-include=true

mp.messaging.incoming.temperature-updates.connector=smallrye-rabbitmq
mp.messaging.incoming.temperature-updates.exchange.name=temperature
mp.messaging.incoming.temperature-updates.queue.name=thermostat
mp.messaging.incoming.temperature-updates.default-routing-key=temperature.sensor
mp.messaging.incoming.temperature-updates.max-incoming-internal-queue-size=1
